# Generated by Django 5.0.6 on 2026-03-08 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_category',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_district',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_login',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_state',
            },
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('crime_id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('complaint_text', models.TextField()),
                ('crime_datetime', models.DateTimeField()),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_district', to='ctapp.district')),
            ],
            options={
                'db_table': 'tbl_crime',
            },
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('fir_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('witness_details', models.TextField()),
                ('evidence_details', models.TextField()),
                ('crime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.crime')),
            ],
            options={
                'db_table': 'tbl_fir',
            },
        ),
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('police_officer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('place', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('mail_id', models.CharField(max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.CharField(blank=True, max_length=50, null=True)),
                ('proof', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('p_type', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.district')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctapp.login')),
            ],
            options={
                'db_table': 'tbl_police_officer',
            },
        ),
        migrations.CreateModel(
            name='CrimeUpdates',
            fields=[
                ('crime_updates_id', models.AutoField(primary_key=True, serialize=False)),
                ('crime_updates', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filedoc', models.CharField(max_length=50, null=True)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.crime')),
                ('police_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctapp.policeofficer')),
            ],
            options={
                'db_table': 'tbl_crime_updates',
            },
        ),
        migrations.AddField(
            model_name='crime',
            name='police_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctapp.policeofficer'),
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('police_station_id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('mail_id', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.district')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctapp.login')),
            ],
            options={
                'db_table': 'tbl_police_station',
            },
        ),
        migrations.AddField(
            model_name='policeofficer',
            name='police_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.policestation'),
        ),
        migrations.AddField(
            model_name='crime',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctapp.policestation'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.state'),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.login')),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=150)),
                ('reply', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctapp.userinfo')),
            ],
            options={
                'db_table': 'tbl_feedback',
            },
        ),
        migrations.AddField(
            model_name='crime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.userinfo'),
        ),
    ]
