# Generated by Django 5.0.6 on 2026-03-12 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='station_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chat_room_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.policestation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.userinfo')),
            ],
            options={
                'db_table': 'tbl_chat_room',
                'unique_together': {('user', 'police_station')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('chat_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_type', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.chatroom')),
            ],
            options={
                'db_table': 'tbl_chat_message',
            },
        ),
    ]
