# Generated by Django 5.0.6 on 2026-03-12 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0002_policestation_station_name_chatroom_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctapp.crime')),
                ('police_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctapp.policestation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctapp.userinfo')),
            ],
            options={
                'db_table': 'tbl_notification',
            },
        ),
    ]
