# Generated by Django 5.0.6 on 2026-03-16 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='policestation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='PanicAlert',
            fields=[
                ('panic_alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='new', max_length=20)),
                ('police_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctapp.policestation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.userinfo')),
            ],
            options={
                'db_table': 'tbl_panic_alert',
            },
        ),
    ]
